# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      mkdir -p ./dags ./logs ./plugins
      echo -e "AIRFLOW_UID=$(id -u)" > .env # runs during prebuild
    command: |
      docker-compose up airflow-init
      docker-compose up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser
  - port: 5555
    onOpen: open-browser
